registers:
  - endpoint: /webhook/alertmanager
    method: POST
    target:
      url: http://localhost:3000/debug
      method: POST
      headers:
        Content-Type: application/json
        X-Custom-Header: "hermes-rs"
    template: |
      {"msg": "Hello {{ escapeNewlines message }}"}

  - endpoint: /webhook/github
    method: POST
    target:
      url: http://localhost:8081/notifications
      method: POST
    template: |
      {
        "event": "{{ action }}",
        "repository": "{{ repository.name }}",
        "sender": "{{ sender.login }}",
        "timestamp": "{{ updated_at }}"
      }

  - endpoint: /webhook/custom
    method: POST
    target:
      url: http://httpbin.org/post
      method: POST
    template: |
      {
        "processed_data": {
          "original": {{ data }},
          "processed_at": "2024-01-01T00:00:00Z"
        }
      }
